### ISSUE TITLE
Incompatible with Raised - 1.19.2

### ISSUE THREAD

**Issue by Nytem** [Terrails/HealthOverlay#46] opened 2023-01-08 10:30 UTC
Idk if this happens on any other versions, haven't tested.

Raised - [https://www.curseforge.com/minecraft/mc-mods/raised](url)

Mixing Health Overlay and Raised causes the game to crash instantly after hitting launch, doesn't give me a crash report. Once I removed raised then the mod started working again with no issues.

**Comment by dirtyfargo** [comment] 2023-01-09 22:02
For me, the issue occurs only with the newest version of Health Overlay (7.2.1), and only when loading a world. I can confirm that when I disable the [Raised](https://www.curseforge.com/minecraft/mc-mods/raised) mod, or revert to version 7.1.1, worlds will load just fine.

[Crash Report ](https://gist.github.com/dirtyfargo/4711d60ca810eca373ac34df3f79a842)

Minecraft           1.19.2
Forge                 43.1.64

**Comment by Nytem** [comment] 2023-01-10 04:45
shoot, should've mentioned I was on Fabric, so could just be a thing there

**Comment by Terrails** [comment] 2023-01-12 14:28
The crash has been fixed on Raised's side, but unfortunately since a lot of changes I made, mainly the custom heart bar positions, you will have to manually move the heart bar using health overlay's config if you want the same height. I am currently working on bringing back compatibility, so do not bug the developer of Raised about this.

**Closed by Terrails** 2023-01-12 14:28 UTC
