### ISSUE TITLE
Armour bar covers absorption hearts when absorption effect is active

### ISSUE THREAD

**Issue by NJL5390** [Terrails/HealthOverlay#7] opened 2020-08-09 11:07 UTC
Minecraft Version: 1.16.1
Forge Version: 32.0.107
Health Overlay Version: 2.1.3

Whenever I'm wearing armour and have absorption at the same time, I have noticed that the armour bar tends to cover the absorption health bar and prevents me from seeing how many absorption hearts I have left, This is especially noticeable after eating a golden apple or enchanted golden apple. This does not occur when Health Overlay is not installed.

With Armour on:
![2020-08-09_11 48 51](https://user-images.githubusercontent.com/64381954/89730518-2cece300-da37-11ea-850c-ab6e4a4f5793.png)

Without Armour on:
![2020-08-09_11 49 30](https://user-images.githubusercontent.com/64381954/89730536-61609f00-da37-11ea-9011-471badd0af1e.png)

**Comment by Terrails** [comment] 2020-08-09 11:35
I think I already know what the issue is, but I can't currently fix it because I'm on vacation. I'll push a fix as soon as I'm back.

**Comment by NJL5390** [comment] 2020-08-09 12:40
No problem man. Just enjoy yourself! :)

**Comment by Terrails** [comment] 2020-08-24 09:38
It should be fixed now.

**Closed** 2020-09-22 09:49 UTC
